services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER}
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../../mlops_data/${POSTGRES_CONTAINER}_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  minio:
    image: quay.io/minio/minio
    depends_on:
      - postgres
    container_name: ${MINIO_CONTAINER}
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_ACCESS_KEY}
      - MINIO_STORAGE_USE_HTTPS=false
    command: server /data --console-address ":9001" 
    volumes:
      - ../../mlops_data/${MINIO_CONTAINER}_data:/data


  minio-setup:
    image: quay.io/minio/mc
    depends_on:
      - postgres
      - minio
    volumes:
      - ./minio/create-bucket.sh:/create-bucket.sh
    entrypoint: /bin/sh
    command: -c "chmod +x ./create-bucket.sh && ./create-bucket.sh"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_ACCESS_KEY}

  
  mlflow:
    restart: always
    build: 
      context: ./mlflow
      dockerfile: Dockerfile
      args: 
        PYTHON_VERSION: ${PYTHON_VERSION}
        MLFLOW_VERSION: ${MLFLOW_VERSION}
    image: mlflow_server
    container_name: ${MLFLOW_CONTAINER}
    ports:
      - "5001:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY} 
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY} 
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000 
      - MLFLOW_S3_IGNORE_TLS=true 
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER}/${POSTGRES_DB} 
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://mlflow-artifacts  
    depends_on:
      - postgres
      - minio-setup  
